#!/usr/bin/env bash
# Contra OTC Demo Setup Script
# This script creates demo token mints, test wallets, and initial balances
# on the local Solana validator used by Contra.
#
# Prerequisites:
#   - Contra docker-compose is running (validator on port 18899)
#   - Solana CLI is installed
#   - jq is installed
#
# Usage: ./scripts/setup-demo.sh

set -euo pipefail

VALIDATOR_URL="http://localhost:18899"
GATEWAY_URL="http://localhost:8899"
OTC_PORT="${OTC_PORT:-3001}"
WS_PORT="${WS_PORT:-3002}"
KEYPAIR_DIR="$(cd "$(dirname "$0")/.." && pwd)/keypairs"
ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env.demo"

echo "============================================"
echo "  Contra OTC Demo Setup"
echo "============================================"
echo ""

# Check that the validator is reachable
echo "Checking local validator at $VALIDATOR_URL..."
if ! curl -s -X POST "$VALIDATOR_URL" -H "Content-Type: application/json" \
     -d '{"jsonrpc":"2.0","id":1,"method":"getSlot"}' --max-time 5 | grep -q result; then
  echo "ERROR: Local validator not reachable at $VALIDATOR_URL"
  echo "Make sure the validator is running on port 18899."
  exit 1
fi
echo "Validator is running."
echo ""

# Create keypair directory
mkdir -p "$KEYPAIR_DIR"

# ---- Helper Functions ----

create_keypair() {
  local name="$1"
  local path="$KEYPAIR_DIR/${name}.json"
  if [ -f "$path" ]; then
    echo "  Keypair $name already exists" >&2
  else
    solana-keygen new -o "$path" --no-bip39-passphrase --force --silent >/dev/null 2>&1
    echo "  Created keypair: $name" >&2
  fi
  echo "$path"
}

get_pubkey() {
  solana-keygen pubkey "$1"
}

airdrop_sol() {
  local pubkey="$1"
  local amount="${2:-10}"
  echo "  Airdropping ${amount} SOL to $pubkey..."
  solana airdrop "$amount" "$pubkey" -u "$VALIDATOR_URL" --commitment confirmed >/dev/null 2>&1 || true
}

# ---- 1. Create Admin/Operator Keypair ----

echo "Step 1: Setting up admin keypair..."
ADMIN_PATH=$(create_keypair "admin")
ADMIN_PUBKEY=$(get_pubkey "$ADMIN_PATH")
echo "  Admin pubkey: $ADMIN_PUBKEY"
airdrop_sol "$ADMIN_PUBKEY" 100
echo ""

# ---- 2. Create Demo Token Mints ----

echo "Step 2: Creating demo token mints..."

# USDC mint (6 decimals)
USDC_MINT_PATH=$(create_keypair "usdc-mint")
USDC_MINT=$(get_pubkey "$USDC_MINT_PATH")
echo "  USDC mint: $USDC_MINT"

# wSOL mint (9 decimals)
WSOL_MINT_PATH=$(create_keypair "wsol-mint")
WSOL_MINT=$(get_pubkey "$WSOL_MINT_PATH")
echo "  wSOL mint: $WSOL_MINT"

# Create mints on local validator
echo "  Creating USDC mint on validator (6 decimals)..."
spl-token create-token --decimals 6 --mint-authority "$ADMIN_PUBKEY" \
  -u "$VALIDATOR_URL" "$USDC_MINT_PATH" \
  --fee-payer "$ADMIN_PATH" 2>/dev/null || echo "  (USDC mint may already exist)"

echo "  Creating wSOL mint on validator (9 decimals)..."
spl-token create-token --decimals 9 --mint-authority "$ADMIN_PUBKEY" \
  -u "$VALIDATOR_URL" "$WSOL_MINT_PATH" \
  --fee-payer "$ADMIN_PATH" 2>/dev/null || echo "  (wSOL mint may already exist)"
echo ""

# ---- 3. Create Test Wallets ----

echo "Step 3: Creating test wallets..."
WALLET_A_PATH=$(create_keypair "wallet-a")
WALLET_A=$(get_pubkey "$WALLET_A_PATH")
echo "  Wallet A: $WALLET_A"
airdrop_sol "$WALLET_A" 50

WALLET_B_PATH=$(create_keypair "wallet-b")
WALLET_B=$(get_pubkey "$WALLET_B_PATH")
echo "  Wallet B: $WALLET_B"
airdrop_sol "$WALLET_B" 50

WALLET_C_PATH=$(create_keypair "wallet-c")
WALLET_C=$(get_pubkey "$WALLET_C_PATH")
echo "  Wallet C: $WALLET_C"
airdrop_sol "$WALLET_C" 50
echo ""

# ---- 4. Create Token Accounts and Mint Initial Balances ----

echo "Step 4: Creating token accounts and minting initial balances..."

for WALLET_PATH in "$WALLET_A_PATH" "$WALLET_B_PATH" "$WALLET_C_PATH"; do
  WALLET_PK=$(get_pubkey "$WALLET_PATH")
  WALLET_NAME=$(basename "$WALLET_PATH" .json)

  echo "  Setting up $WALLET_NAME ($WALLET_PK)..."

  # Create USDC token account
  spl-token create-account "$USDC_MINT" \
    --owner "$WALLET_PK" --fee-payer "$ADMIN_PATH" \
    -u "$VALIDATOR_URL" 2>/dev/null || true

  # Create wSOL token account
  spl-token create-account "$WSOL_MINT" \
    --owner "$WALLET_PK" --fee-payer "$ADMIN_PATH" \
    -u "$VALIDATOR_URL" 2>/dev/null || true

  # Mint USDC (10,000 USDC = 10000 * 10^6)
  echo "    Minting 10,000 USDC..."
  spl-token mint "$USDC_MINT" 10000000000 \
    --recipient-owner "$WALLET_PK" --mint-authority "$ADMIN_PATH" \
    -u "$VALIDATOR_URL" --fee-payer "$ADMIN_PATH" 2>/dev/null || true

  # Mint wSOL (100 SOL = 100 * 10^9)
  echo "    Minting 100 wSOL..."
  spl-token mint "$WSOL_MINT" 100000000000 \
    --recipient-owner "$WALLET_PK" --mint-authority "$ADMIN_PATH" \
    -u "$VALIDATOR_URL" --fee-payer "$ADMIN_PATH" 2>/dev/null || true
done
echo ""

# ---- 5. Write Environment File ----

echo "Step 5: Writing environment file..."
cat > "$ENV_FILE" << EOF
# Contra OTC Demo Environment
# Generated by setup-demo.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Token Mints
DEMO_USDC_MINT=$USDC_MINT
DEMO_WSOL_MINT=$WSOL_MINT
DEMO_TOKEN_MINTS=$USDC_MINT,$WSOL_MINT

# Admin
ADMIN_KEYPAIR_PATH=$ADMIN_PATH
ADMIN_PUBKEY=$ADMIN_PUBKEY

# Test Wallets
WALLET_A=$WALLET_A
WALLET_B=$WALLET_B
WALLET_C=$WALLET_C

# URLs
CONTRA_GATEWAY_URL=$GATEWAY_URL
SOLANA_VALIDATOR_URL=$VALIDATOR_URL

# OTC Server
OTC_PORT=$OTC_PORT

# Frontend (add these to otc-frontend/.env)
VITE_DEMO_TOKEN_MINTS=$USDC_MINT,$WSOL_MINT
EOF

echo "  Wrote $ENV_FILE"
echo ""

# ---- 6. Create frontend env ----

FRONTEND_ENV="$(cd "$(dirname "$0")/.." && pwd)/otc-frontend/.env"
cat > "$FRONTEND_ENV" << EOF
VITE_API_PROXY_TARGET=http://localhost:$OTC_PORT
VITE_WS_URL=ws://localhost:$WS_PORT
VITE_CONTRA_GATEWAY_URL=$GATEWAY_URL
VITE_SOLANA_VALIDATOR_URL=$VALIDATOR_URL
VITE_DEMO_TOKEN_MINTS=$USDC_MINT,$WSOL_MINT
EOF
echo "  Wrote $FRONTEND_ENV"

echo ""
echo "============================================"
echo "  Setup Complete!"
echo "============================================"
echo ""
echo "Token Mints:"
echo "  USDC: $USDC_MINT"
echo "  wSOL: $WSOL_MINT"
echo ""
echo "Test Wallets (each has 10,000 USDC + 100 wSOL):"
echo "  A: $WALLET_A"
echo "  B: $WALLET_B"
echo "  C: $WALLET_C"
echo ""
echo "Next steps:"
echo "  1. Start the OTC server:"
echo "     cd otc-server && DEMO_TOKEN_MINTS=$USDC_MINT,$WSOL_MINT npm run dev"
echo "  2. Start the frontend:"
echo "     cd otc-frontend && npm run dev"
echo "  3. Open http://localhost:5173 and connect a wallet"
echo ""
